version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install g++
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Install sdl2
          command: 'apt-get update && apt-get install -y libsdl2-dev'

      - run:
          name: Install make
          command: 'apt-get update && apt-get install -y make'

      - run:
          name: Actual Build
          command: 'make'

          
