version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Install make
          command: 'apt-get update && apt-get install -y make'

      - run:
          name: Actual Build
          command: 'make'

          
